### PR TITLE
Certora's Formal Verification for Comet protocol (#288)

### PR DESCRIPTION
**Pull request by jflatow**
Cleaning up / merging Certora's branch

Co-authored-by: Nurit Dor <nurit@certora.com>
Co-authored-by: Gadi Rechlis <gadi@certora.com>
Co-authored-by: Nurit Dor <57101353+nd-certora@users.noreply.github.com>
Co-authored-by: Yura Sherman <yurasherman+github@gmail.com>
Co-authored-by: fnast9 <anastasia@certora.com>

### CODE REVIEW

**Comment by jflatow** [comment]
I suggest we close / re-open this one as a PR from the remote origin (https://github.com/certora/comet) instead of trying to sync to a branch here

**Comment by MichaelMorami** [comment]
> I suggest we close / re-open this one as a PR from the remote origin (https://github.com/certora/comet) instead of trying to sync to a branch here

would you prefer if i close this one and make a new PR directly from the branch on our fork?

**Comment by MichaelMorami** [comment]
> > > I suggest we close / re-open this one as a PR from the remote origin (https://github.com/certora/comet) instead of trying to sync to a branch here
> > 
> > 
> > would you prefer if i close this one and make a new PR directly from the branch on our fork?
> 
> Yea that's what I'm suggesting, it should be cleaner/easier

On it.

**Comment by jflatow** [comment]
Nice, thanks! 🙌

**Pull request closed without merging**
