### PR TITLE
Explicit supply cap constraint for failing bulker scen

### PR DESCRIPTION
**Pull request by jflatow**

### CODE REVIEW

**Review by scott-silver — APPROVED** [review]
👍

**Comment by scott-silver** [comment]
same change needed for `'Comet#bulker > (non-WETH base) all actions in one txn'`?

**Review by kevincheng96 — APPROVED** [review]
Nice fix. +1 🥈's comment

**Comment by jflatow** [comment]
> is the same change needed for `'Comet#bulker > (non-WETH base) all actions in one txn'`?

It doesn't seem to be

**Pull request merged**
